// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamApp.WebAPI.Context;

#nullable disable

namespace SteamApp.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260118104820_db_v2.1")]
    partial class db_v21
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SteamApp.Models.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("base_url");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("game");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.GameUrl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("EndPage")
                        .HasColumnType("int")
                        .HasColumnName("end_page");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsBatchUrl")
                        .HasColumnType("bit")
                        .HasColumnName("is_batch_url");

                    b.Property<bool>("IsPixelScrape")
                        .HasColumnType("bit")
                        .HasColumnName("is_pixel_scrape");

                    b.Property<string>("PartialUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partial_url");

                    b.Property<int?>("StartPage")
                        .HasColumnType("int")
                        .HasColumnName("start_page");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("game_url");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.Pixel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GameUrlId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_url_id");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("GameUrlId");

                    b.ToTable("pixel");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GameUrlId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_url_id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("GameUrlId");

                    b.ToTable("product");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.WatchList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("batch_url");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<long?>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<long?>("GameUrlId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_url_id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("rd");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameUrlId");

                    b.ToTable("watch_list");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.WishList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("wish_list");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.GameUrl", b =>
                {
                    b.HasOne("SteamApp.Models.Entities.Game", "Game")
                        .WithMany("GameUrls")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.Pixel", b =>
                {
                    b.HasOne("SteamApp.Models.Entities.GameUrl", "GameUrl")
                        .WithMany("Pixels")
                        .HasForeignKey("GameUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameUrl");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.Product", b =>
                {
                    b.HasOne("SteamApp.Models.Entities.GameUrl", "GameUrl")
                        .WithMany("Products")
                        .HasForeignKey("GameUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameUrl");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.WatchList", b =>
                {
                    b.HasOne("SteamApp.Models.Entities.Game", "Game")
                        .WithMany("WatchLists")
                        .HasForeignKey("GameId");

                    b.HasOne("SteamApp.Models.Entities.GameUrl", "GameUrl")
                        .WithMany("WatchLists")
                        .HasForeignKey("GameUrlId");

                    b.Navigation("Game");

                    b.Navigation("GameUrl");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.WishList", b =>
                {
                    b.HasOne("SteamApp.Models.Entities.Game", "Game")
                        .WithMany("WishLists")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.Game", b =>
                {
                    b.Navigation("GameUrls");

                    b.Navigation("WatchLists");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.GameUrl", b =>
                {
                    b.Navigation("Pixels");

                    b.Navigation("Products");

                    b.Navigation("WatchLists");
                });
#pragma warning restore 612, 618
        }
    }
}
