// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamApp.WebAPI.Context;

#nullable disable

namespace SteamApp.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113211834_db1.2")]
    partial class db12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SteamApp.Models.Entities.ExtraPixel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GameUrlId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_url_id");

                    b.Property<long>("PixelValue")
                        .HasColumnType("bigint")
                        .HasColumnName("pixel_value");

                    b.HasKey("Id");

                    b.HasIndex("GameUrlId");

                    b.ToTable("extra_pixel");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("base_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("game");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.GameUrl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("EndPage")
                        .HasColumnType("int")
                        .HasColumnName("end_page");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsBatchUrl")
                        .HasColumnType("bit")
                        .HasColumnName("is_batch_url");

                    b.Property<bool>("IsPixelScrape")
                        .HasColumnType("bit")
                        .HasColumnName("is_pixel_scrape");

                    b.Property<string>("PartialUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partial_url");

                    b.Property<int?>("StartPage")
                        .HasColumnType("int")
                        .HasColumnName("start_page");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("game_urls");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GameUrlId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_url_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("GameUrlId");

                    b.ToTable("product");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.WatchListItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("batch_url");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<long?>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<long?>("GameUrlId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_url_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("rd");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("watch_list");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.WishListItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("wish_list");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.ExtraPixel", b =>
                {
                    b.HasOne("SteamApp.Models.Entities.GameUrl", null)
                        .WithMany("ExtraPixels")
                        .HasForeignKey("GameUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamApp.Models.Entities.GameUrl", b =>
                {
                    b.HasOne("SteamApp.Models.Entities.Game", null)
                        .WithMany("GameUrls")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamApp.Models.Entities.Product", b =>
                {
                    b.HasOne("SteamApp.Models.Entities.GameUrl", null)
                        .WithMany("Products")
                        .HasForeignKey("GameUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamApp.Models.Entities.WatchListItem", b =>
                {
                    b.HasOne("SteamApp.Models.Entities.Game", null)
                        .WithMany("WatchListItems")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.WishListItem", b =>
                {
                    b.HasOne("SteamApp.Models.Entities.Game", null)
                        .WithMany("WishListItems")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamApp.Models.Entities.Game", b =>
                {
                    b.Navigation("GameUrls");

                    b.Navigation("WatchListItems");

                    b.Navigation("WishListItems");
                });

            modelBuilder.Entity("SteamApp.Models.Entities.GameUrl", b =>
                {
                    b.Navigation("ExtraPixels");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
