// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamApp.WebAPI.Context;

#nullable disable

namespace SteamApp.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SteamApp.Domain.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("base_url");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("PageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("page_url");

                    b.HasKey("Id");

                    b.ToTable("game");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.GameAddOn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("game_add_on");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.GameUrl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("EndPage")
                        .HasColumnType("int")
                        .HasColumnName("end_page");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsBatchUrl")
                        .HasColumnType("bit")
                        .HasColumnName("is_batch_url");

                    b.Property<bool>("IsPixelScrape")
                        .HasColumnType("bit")
                        .HasColumnName("is_pixel_scrape");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("PartialUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partial_url");

                    b.Property<int?>("StartPage")
                        .HasColumnType("int")
                        .HasColumnName("start_page");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("game_url");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.GameUrlPixels", b =>
                {
                    b.Property<long>("PixelId")
                        .HasColumnType("bigint")
                        .HasColumnName("pixel_id");

                    b.Property<long>("GameUrlId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_url_id");

                    b.HasKey("PixelId", "GameUrlId");

                    b.HasIndex("GameUrlId");

                    b.ToTable("game_url_pixels");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.GameUrlProducts", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("GameUrlId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_url_id");

                    b.HasKey("ProductId", "GameUrlId");

                    b.HasIndex("GameUrlId");

                    b.ToTable("game_url_products");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.Pixel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BlueValue")
                        .HasColumnType("bigint")
                        .HasColumnName("b_value");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<long>("GreenValue")
                        .HasColumnType("bigint")
                        .HasColumnName("g_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<long>("RedValue")
                        .HasColumnType("bigint")
                        .HasColumnName("r_value");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("pixel");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("product");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.ProductTags", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("product_tags");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("tag");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.WatchList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BatchNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_number");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<long>("GameUrlId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_url_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("rd");

                    b.HasKey("Id");

                    b.HasIndex("GameUrlId");

                    b.HasIndex("ProductId");

                    b.ToTable("watch_list");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.WishList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("wish_list");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.GameAddOn", b =>
                {
                    b.HasOne("SteamApp.Domain.Entities.Game", "Game")
                        .WithMany("GameAddOns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.GameUrl", b =>
                {
                    b.HasOne("SteamApp.Domain.Entities.Game", "Game")
                        .WithMany("GameUrls")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.GameUrlPixels", b =>
                {
                    b.HasOne("SteamApp.Domain.Entities.GameUrl", "GameUrl")
                        .WithMany("GameUrlsPixels")
                        .HasForeignKey("GameUrlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SteamApp.Domain.Entities.Pixel", "Pixel")
                        .WithMany("GameUrlsPixels")
                        .HasForeignKey("PixelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameUrl");

                    b.Navigation("Pixel");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.GameUrlProducts", b =>
                {
                    b.HasOne("SteamApp.Domain.Entities.GameUrl", "GameUrl")
                        .WithMany("GameUrlsProducts")
                        .HasForeignKey("GameUrlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SteamApp.Domain.Entities.Product", "Product")
                        .WithMany("GameUrlsProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameUrl");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.Pixel", b =>
                {
                    b.HasOne("SteamApp.Domain.Entities.Game", "Game")
                        .WithMany("Pixels")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.Product", b =>
                {
                    b.HasOne("SteamApp.Domain.Entities.Game", "Game")
                        .WithMany("Products")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.ProductTags", b =>
                {
                    b.HasOne("SteamApp.Domain.Entities.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SteamApp.Domain.Entities.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.Tag", b =>
                {
                    b.HasOne("SteamApp.Domain.Entities.Game", "Game")
                        .WithMany("Tags")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.WatchList", b =>
                {
                    b.HasOne("SteamApp.Domain.Entities.GameUrl", "GameUrl")
                        .WithMany("WatchLists")
                        .HasForeignKey("GameUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamApp.Domain.Entities.Product", "Product")
                        .WithMany("WatchLists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameUrl");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.WishList", b =>
                {
                    b.HasOne("SteamApp.Domain.Entities.Game", "Game")
                        .WithMany("WishLists")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.Game", b =>
                {
                    b.Navigation("GameAddOns");

                    b.Navigation("GameUrls");

                    b.Navigation("Pixels");

                    b.Navigation("Products");

                    b.Navigation("Tags");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.GameUrl", b =>
                {
                    b.Navigation("GameUrlsPixels");

                    b.Navigation("GameUrlsProducts");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.Pixel", b =>
                {
                    b.Navigation("GameUrlsPixels");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.Product", b =>
                {
                    b.Navigation("GameUrlsProducts");

                    b.Navigation("ProductTags");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("SteamApp.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
