// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamAppServer.Context;

#nullable disable

namespace SteamAppServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SteamAppServer.Models.Quality", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("quality");
                });

            modelBuilder.Entity("SteamAppServer.Models.SellListing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("DateBought")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_bought");

                    b.Property<DateTime?>("DateSold")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_sold");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("desciption");

                    b.Property<bool>("IsHat")
                        .HasColumnType("bit")
                        .HasColumnName("is_hat");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit")
                        .HasColumnName("is_sold");

                    b.Property<bool>("IsWeapon")
                        .HasColumnType("bit")
                        .HasColumnName("is_weapon");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<short>("QualityId")
                        .HasColumnType("smallint")
                        .HasColumnName("quality_id");

                    b.Property<decimal?>("SoldPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sold_price");

                    b.Property<decimal>("TargetSellPrice1")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("t_sell_price_1");

                    b.Property<decimal?>("TargetSellPrice2")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("t_sell_price_2");

                    b.Property<decimal?>("TargetSellPrice3")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("t_sell_price_3");

                    b.Property<decimal?>("TargetSellPrice4")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("t_sell_price_4");

                    b.HasKey("Id");

                    b.HasIndex("QualityId");

                    b.ToTable("sell_listing");
                });

            modelBuilder.Entity("SteamAppServer.Models.SellListing", b =>
                {
                    b.HasOne("SteamAppServer.Models.Quality", "Quality")
                        .WithMany()
                        .HasForeignKey("QualityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quality");
                });
#pragma warning restore 612, 618
        }
    }
}
