services:
  steamapp-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - steamapp-redis-data:/data
    restart: unless-stopped

  steamapp-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - ./env/sqlserver.env
    ports:
      - "14333:1433"
    volumes:
      - steamapp-sql-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  steamapp-redis-data:
  steamapp-sql-data:
