apiVersion: v1
kind: Secret
metadata:
  name: steamapp-local-secret
  namespace: steamapp-local
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: Change_this_password_123!
  ConnectionStrings__DefaultConnection: Server=steamapp-sql,1433;Database=SteamAppDb;User Id=sa;Password=Change_this_password_123!;TrustServerCertificate=True;Encrypt=True;
  JwtSettings__Key: local-k8s-jwt-signing-key-at-least-32-bytes-long
  Clients__0__ClientSecret: dev-client-secret
  Clients__1__ClientSecret: dev-internal-secret
  RabbitMq__UserName: steamapp
  RabbitMq__Password: steamapp-rabbitmq-password
