// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamApp.Context;

#nullable disable

namespace SteamApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250623204218_item-class-and-slot")]
    partial class itemclassandslot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SteamApp.Models.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsWeapon")
                        .HasColumnType("bit")
                        .HasColumnName("is_weapon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<long>("SlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("slot_id");

                    b.HasKey("Id");

                    b.ToTable("item");
                });

            modelBuilder.Entity("SteamApp.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("DateBought")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_bought");

                    b.Property<DateTime?>("DateSold")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_sold");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("desciption");

                    b.Property<bool>("IsHat")
                        .HasColumnType("bit")
                        .HasColumnName("is_hat");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit")
                        .HasColumnName("is_sold");

                    b.Property<bool>("IsWeapon")
                        .HasColumnType("bit")
                        .HasColumnName("is_weapon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<short?>("QualityId")
                        .HasColumnType("smallint")
                        .HasColumnName("quality_id");

                    b.Property<decimal?>("SoldPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sold_price");

                    b.Property<decimal?>("TargetSellPrice1")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("t_sell_price_1");

                    b.Property<decimal?>("TargetSellPrice2")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("t_sell_price_2");

                    b.Property<decimal?>("TargetSellPrice3")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("t_sell_price_3");

                    b.Property<decimal?>("TargetSellPrice4")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("t_sell_price_4");

                    b.HasKey("Id");

                    b.ToTable("product");
                });
#pragma warning restore 612, 618
        }
    }
}
