SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @UserId nvarchar(450) = N'REPLACE_WITH_USER_ID';
DECLARE @GameId bigint;
DECLARE @TagId bigint;
DECLARE @InsertedProducts int = 0;
DECLARE @InsertedProductTags int = 0;

IF @UserId = N'REPLACE_WITH_USER_ID' OR NULLIF(LTRIM(RTRIM(@UserId)), N'') IS NULL
    THROW 50000, 'Set @UserId before running this script.', 1;

IF (SELECT COUNT(*)
    FROM dbo.game
    WHERE name = N'Team Fortress 2'
      AND user_id = @UserId) <> 1
    THROW 50001, 'Expected exactly one Team Fortress 2 game for @UserId.', 1;

SELECT @GameId = id
FROM dbo.game
WHERE name = N'Team Fortress 2'
  AND user_id = @UserId;

IF (SELECT COUNT(*)
    FROM dbo.tag
    WHERE game_id = @GameId
      AND name = N'Hat'
      AND user_id = @UserId) <> 1
    THROW 50002, 'Expected exactly one Hat tag for the Team Fortress 2 game and @UserId.', 1;

SELECT @TagId = id
FROM dbo.tag
WHERE game_id = @GameId
  AND name = N'Hat'
  AND user_id = @UserId;

DECLARE @ProductNames table
(
    name nvarchar(255) NOT NULL PRIMARY KEY
);

INSERT INTO @ProductNames (name)
VALUES
    (N'Bald Spotter'),
    (N'Barbeque Bacon Britches'),
    (N'Inglorious Patriot'),
    (N'The Deadliest Match'),
    (N'The Long Shot'),
    (N'The Night Riders'),
    (N'The Unknown Warrior'),
    (N'Tropical Torcher'),
    (N'Unruly Ruler'),
    (N'Vested Investor''s Vest'),
    (N'Atomic Bomber'),
    (N'Bomb Blanket'),
    (N'Delusions of Grandeur'),
    (N'Lieutenant''s Cut'),
    (N'Standing Offer'),
    (N'Surgical Shroud'),
    (N'The Handsome Ranger'),
    (N'Tsar Athlete'),
    (N'Beachcomber''s Brim'),
    (N'Bonk! Atomic Kicks'),
    (N'Chief Executor'),
    (N'Deadwave Communicator'),
    (N'Hard Hearing'),
    (N'Pyro''s Overalls'),
    (N'Air Exchanger'),
    (N'Feathered Foe'),
    (N'Poncho del Pesado'),
    (N'Professor Photon'),
    (N'Seamann''s Stubble'),
    (N'Service Satchel'),
    (N'Technician''s Tunic'),
    (N'The Misdirector'),
    (N'Torn Terror'),
    (N'Viscera Visor'),
    (N'El Gigante''s Gunbelt'),
    (N'Heat Shield'),
    (N'Industrial Insurgent'),
    (N'Mad Drip'),
    (N'Pantaloons of Unabashed Villainy'),
    (N'Ripped Runts'),
    (N'Sleight of Hand'),
    (N'Buzz Kill'),
    (N'Cigarillo Caballero'),
    (N'Vanishing Act'),
    (N'Velveteen Villain'),
    (N'Fused Plates'),
    (N'Hellscape'),
    (N'Cattleman''s Kettle'),
    (N'Clinical Investigator'),
    (N'Esprit De Corps'),
    (N'Frogmann''s Fittings'),
    (N'Hunk Of Monk'),
    (N'Jarhead'),
    (N'Le Sapeur'),
    (N'Mann of the Hour'),
    (N'Shady Shelby'),
    (N'Spy Ties'),
    (N'Blindin'' Bonnett'),
    (N'Fat Friar'),
    (N'Hardcore Pantalon'),
    (N'Le Morne Uniforme'),
    (N'Oxygen Provider'),
    (N'Shadow of Doubt'),
    (N'Sir Buildsalot'),
    (N'The Headliner'),
    (N'Case of the Blues'),
    (N'Mr. Rostov'),
    (N'Short Fuse'),
    (N'The Abyss Diver'),
    (N'Team Cap'),
    (N'Air Head'),
    (N'Alpine Apparel'),
    (N'Black Tie Affair'),
    (N'Deserter''s Duster'),
    (N'Epilogue Locks'),
    (N'Lazer Gazers'),
    (N'Puncher''s Polar Puffer'),
    (N'Scrub Stompers'),
    (N'Snow Merc'),
    (N'Sydney Shearling'),
    (N'Alpine Hawk'),
    (N'Aristocravat'),
    (N'Chill-Seeker'),
    (N'Commonwealth Commander'),
    (N'Festive Fleece'),
    (N'Flatline Flatcap'),
    (N'Scrooge McCrocket'),
    (N'The Sole Providers'),
    (N'Blizzard Bonnet'),
    (N'Cardiologist''s Cardigan'),
    (N'Veteran''s Visor'),
    (N'Willis'' Warmer'),
    (N'The Old Days Devotion'),
    (N'Brute''s Braces'),
    (N'Commonwealth Commando'),
    (N'Daring Dell'),
    (N'Desk Engineer'),
    (N'Invisible Flame'),
    (N'Pathfinder'),
    (N'The Aimframe'),
    (N'The Brand Loyalist'),
    (N'The Vaudeville Visor'),
    (N'Watchmann''s Wetsuit'),
    (N'Crook''s Cap'),
    (N'Justice Johns'),
    (N'Scorched Earth Stompers'),
    (N'Sneaky Blinder'),
    (N'Tanker''s Top'),
    (N'The Big Star'),
    (N'The Tropical Brim'),
    (N'Control Patrol'),
    (N'Fire Marshal'),
    (N'Free Mann''s Fashion'),
    (N'Tuxedo Royale'),
    (N'Botler 2000'),
    (N'Hazardous Environment Vest'),
    (N'Defaced Detonator'),
    (N'Dusk Duster'),
    (N'Fleet Commander'),
    (N'Mannhattan Protect'),
    (N'Nightfall Veil'),
    (N'School Nuisance'),
    (N'Spider Sights'),
    (N'The Strikeout'),
    (N'The Witch Doctor'),
    (N'Triboniophorus Gentlemannus'),
    (N'Delldozer'),
    (N'Hellish Overlord'),
    (N'Nuclear Necessity'),
    (N'Shadow Shroud'),
    (N'Strigoi Stare'),
    (N'The Surgeon General'),
    (N'Badlands Bandido'),
    (N'Chiromancer''s Kit'),
    (N'Contaminated Carryall'),
    (N'Duality of Mantle'),
    (N'Sear Seer'),
    (N'Commanding Presence'),
    (N'Consigliere''s Coverup'),
    (N'Dapper Noel'),
    (N'Field Fatigues'),
    (N'Hot Spaniel'),
    (N'Poleur Voyeur'),
    (N'Snug Sharpshooter'),
    (N'The Battle Music'),
    (N'The Crimbo Cap'),
    (N'The Westcoat'),
    (N'Buck''s Brim'),
    (N'Cossack Camo'),
    (N'Frostbite Fit'),
    (N'Le Frosteaux'),
    (N'Mine Sweepers'),
    (N'Polar Charger'),
    (N'The Checkered Past'),
    (N'The Triple Jumper'),
    (N'Battle Balaclava'),
    (N'L''aire Filteure'),
    (N'Scrooge McDoc'),
    (N'The Top Brass'),
    (N'The Necroprancer'),
    (N'Concealed Convict'),
    (N'Constructor''s Cover'),
    (N'Ludicrously Lunatic Lunon Fedora'),
    (N'Medical Mummy'),
    (N'Shortness Of Breath'),
    (N'Six-Eyed Specs'),
    (N'Splitting Headache'),
    (N'The Make Ogre'),
    (N'The Mean Captain'),
    (N'Thunder Dome'),
    (N'Classic Criminal'),
    (N'Dead Heat'),
    (N'Dell Dynamic'),
    (N'Jumping Jester'),
    (N'Sharpshooter''s Shroud'),
    (N'Stunt Suit'),
    (N'The Main Cast'),
    (N'Warlock''s Warcloak'),
    (N'Clown''s Cover-Up'),
    (N'Mad Lad'),
    (N'Power Spike'),
    (N'Sightseer'),
    (N'The Last Laugh'),
    (N'Bare Bear Bones'),
    (N'Demonic Dome'),
    (N'Brimmed Bootlegger'),
    (N'Brothers in Blues'),
    (N'Cargo Constructor'),
    (N'Heavy Metal'),
    (N'Le Professionnel'),
    (N'Medical Emergency'),
    (N'Stealth Bomber'),
    (N'The Blast Bowl'),
    (N'The Bushman'),
    (N'The Firestalker'),
    (N'Cleaner''s Cap'),
    (N'Close Quarters Cover'),
    (N'Hazard Handler'),
    (N'Hog Heels'),
    (N'Preventative Measure'),
    (N'Prohibition Opposition'),
    (N'The Shrapnel Shell'),
    (N'The Soho Sleuth'),
    (N'Brother Mann'),
    (N'Cranium Cover'),
    (N'The Flame Warrior'),
    (N'The Glorious Gambeson'),
    (N'Über-Wear'),
    (N'Cranium Cooler'),
    (N'Full Metal Helmet'),
    (N'Balkan''s Brute'),
    (N'Bigger Mann on Campus'),
    (N'Cozy Cover-Up'),
    (N'Impact Impaler'),
    (N'Nightcap'),
    (N'Rugged Rags'),
    (N'Sleuth Suit'),
    (N'The Covert Covers'),
    (N'The Puffed Practitioner'),
    (N'Wanderer''s Wool'),
    (N'Clue Hairdo'),
    (N'Isotopic Insulator'),
    (N'Slumber Slacks'),
    (N'Strasbourg Scholar'),
    (N'The Frigid Fashion'),
    (N'Torcher''s Trench Coat'),
    (N'Trench Warfarer'),
    (N'Bonk Beanie'),
    (N'Lazy Lounger'),
    (N'Masked Loyalty'),
    (N'The Dapper Dickens'),
    (N'Boarder''s Beanie'),
    (N'Scruffed ''n Stitched'),
    (N'Beaten and Bruised'),
    (N'Bombard Brigadier'),
    (N'Firearm Protector'),
    (N'Horror Shawl'),
    (N'Hunting Cloak'),
    (N'More Gun Marshal'),
    (N'Nightbane Brim'),
    (N'Starlight Sorcerer'),
    (N'The Imp''s Imprint'),
    (N'The Turncoat'),
    (N'Dustbowl Devil'),
    (N'Headhunter''s Brim'),
    (N'Road Block'),
    (N'Safety Stripes'),
    (N'The Lavish Labwear'),
    (N'The Masked Fiend'),
    (N'Alcoholic Automaton'),
    (N'Cranial Cowl'),
    (N'Road Rage'),
    (N'Victorian Villainy'),
    (N'Propaniac'),
    (N'The Onimann'),
    (N'Barefoot Brawler'),
    (N'Combat Casual'),
    (N'Hawaiian Hunter'),
    (N'Pest''s Pads'),
    (N'Tactical Turtleneck'),
    (N'The Chaser'),
    (N'The Team Player'),
    (N'The Throttlehead'),
    (N'The Western Wraps'),
    (N'Undercover Brolly'),
    (N'Boston Brain Bucket'),
    (N'Fizzy Pharmacist'),
    (N'Squatter''s Right'),
    (N'The Detective'),
    (N'The Hawaiian Hangover'),
    (N'The Lawnmaker'),
    (N'The Ripped Rider'),
    (N'Tropical Camo'),
    (N'Head Banger'),
    (N'Kazan Karategi'),
    (N'Monsieur Grenouille'),
    (N'Night Vision Gawkers'),
    (N'Soda Cap'),
    (N'Rocko'),
    (N'The Decorated Veteran'),
    (N'Arctic Mole'),
    (N'Bulb Bonnet'),
    (N'Cold Blooded Coat'),
    (N'Crosshair Cardigan'),
    (N'Glasgow Bankroll'),
    (N'Heavy Heating'),
    (N'Lumbercap'),
    (N'Oktoberfester'),
    (N'Partizan'),
    (N'The Soft Hard Hat'),
    (N'Firebrand'),
    (N'Frostbite Bonnet'),
    (N'Infiltrator''s Insulation'),
    (N'Ol'' Reliable'),
    (N'Plaid Lad'),
    (N'The Cool Warm Sweater'),
    (N'Underminer''s Overcoat'),
    (N'Battle Bear'),
    (N'Colonel Kringle'),
    (N'Motley Sleeves'),
    (N'The Wooly Pulli'),
    (N'Festive Rack'),
    (N'Trapper''s Flap'),
    (N'Beanie The All-Gnawing'),
    (N'Creepy Crawlers'),
    (N'Death Stare'),
    (N'Hat Outta Hell'),
    (N'Smiling Somen'),
    (N'Spooky Head-Bouncers'),
    (N'The Scariest Mask EVER'),
    (N'Trickster''s Treats'),
    (N'Twisted Topper'),
    (N'Alakablamicon'),
    (N'Eyequarium'),
    (N'Goalkeeper'),
    (N'Optic Nerve'),
    (N'Second-Head Headwear'),
    (N'The Hook, Line, and Thinker'),
    (N'Gruesome Gourd'),
    (N'The Bone Cone'),
    (N'Wandering Wraith'),
    (N'Towering Patch of Pumpkins'),
    (N'Brim of Fire'),
    (N'Fried Batter'),
    (N'Hook, Line, and Cinder'),
    (N'Manndatory Attire'),
    (N'Reel Fly Hat'),
    (N'Roaming Roman'),
    (N'Thousand-Yard Stare'),
    (N'Two Punch Mann'),
    (N'Wild Brim Slouch'),
    (N'Crocodile Dandy'),
    (N'Meal Dealer'),
    (N'Snack Stack'),
    (N'The Sightliner'),
    (N'Water Waders'),
    (N'Crustaceous Cowl'),
    (N'Fast Food'),
    (N'The Panisher'),
    (N'Ballooniphones'),
    (N'Brain Cane'),
    (N'Cozy Catchers'),
    (N'El Fiestibrero'),
    (N'Elf Defense'),
    (N'Festive Cover-Up'),
    (N'Festive Frames'),
    (N'Gnome Dome'),
    (N'Mooshanka'),
    (N'Ominous Offering'),
    (N'The Giftcrafter'),
    (N'Elf Ignition'),
    (N'Elf-Made Bandanna'),
    (N'Reindoonihorns'),
    (N'Seasonal Employee'),
    (N'Seasonal Spring'),
    (N'Train Of Thought'),
    (N'Hat Chocolate'),
    (N'Jolly Jester'),
    (N'Merry Cone'),
    (N'Oh Deer!'),
    (N'Bazaar Bauble'),
    (N'California Cap'),
    (N'Crabe de Chapeau'),
    (N'Fire Fighter'),
    (N'Head Of Defense'),
    (N'Poolside Polo'),
    (N'Self-Care'),
    (N'Soda Specs'),
    (N'Sophisticated Smoker'),
    (N'The Jarmaments'),
    (N'Bird''s Eye Viewer'),
    (N'Breach and Bomb'),
    (N'Flatliner'),
    (N'Hazard Headgear'),
    (N'Momma Kiev'),
    (N'Tools of the Tourist'),
    (N'Flamehawk'),
    (N'Hawk Warrior'),
    (N'Loaf Loafers'),
    (N'Smoking Jacket'),
    (N'Breadcrab'),
    (N'Hypno-Eyes'),
    (N'A Handsome Handy Thing'),
    (N'Calamitous Cauldron'),
    (N'Flavorful Baggies'),
    (N'Goblineer'),
    (N'Handsome Devil'),
    (N'Hollowed Helm'),
    (N'King Cardbeard'),
    (N'The Boom Boxers'),
    (N'The Ghoul Box'),
    (N'The Seared Sorcerer'),
    (N'Eye-See-You'),
    (N'Glow from Below'),
    (N'Gourd Grin'),
    (N'Impish Ears'),
    (N'Semi-Tame Trapper''s Hat'),
    (N'Sir Pumpkinton'),
    (N'Misfortune Fedora'),
    (N'The Fire Tooth'),
    (N'Wavefinder'),
    (N'Wrap-A-Khamon'),
    (N'All Hallows'' Hatte'),
    (N'Balloonicorpse'),
    (N'Bear Walker'),
    (N'Candy Cantlers'),
    (N'Elf Care Provider'),
    (N'Festive Fascinator'),
    (N'Festive Flip-thwomps'),
    (N'Jolly Jingler'),
    (N'Particulate Protector'),
    (N'Reindoonibeanie'),
    (N'Shoestring Santa'),
    (N'The Killing Tree'),
    (N'BedBug Protection'),
    (N'Blitzen Bowl'),
    (N'Night Ward'),
    (N'Professional''s Pom-Pom'),
    (N'SandMann''s Brush'),
    (N'The Smissmas Sorcerer'),
    (N'Helm Helm'),
    (N'The Round-A-Bout'),
    (N'Towering Pillar of Beanies'),
    (N'Towering Pile Of Presents'),
    (N'Bat Hat'),
    (N'BINOCULUS!'),
    (N'Bread Biter'),
    (N'Candy Cranium'),
    (N'Convict Cap'),
    (N'Derangement Garment'),
    (N'El Mostacho'),
    (N'Fuel Injector'),
    (N'Party Poncho'),
    (N'Pocket Halloween Boss'),
    (N'El Zapateador'),
    (N'Madmann''s Muzzle'),
    (N'Skullbrero'),
    (N'Soviet Strongmann'),
    (N'The Horrible Horns'),
    (N'Voodoo Vizier'),
    (N'Elizabeth the Third'),
    (N'Head of the Dead'),
    (N'Racc Mann'),
    (N'The Trick Stabber'),
    (N'Mister Bones'),
    (N'Pyr''o Lantern'),
    (N'Backbreaker''s Guards'),
    (N'Brain Interface'),
    (N'Dancing Doe'),
    (N'Mediterranean Mercenary'),
    (N'Melted Mop'),
    (N'Shutterbug'),
    (N'Stapler''s Specs'),
    (N'The Bottle Cap'),
    (N'The Pompous Privateer'),
    (N'Wanderer''s Wear'),
    (N'Backbreaker''s Skullcracker'),
    (N'Dynamite Abs'),
    (N'Kapitan''s Kaftan'),
    (N'Spawn Camper'),
    (N'Speedy Scoundrel'),
    (N'Wagga Wagga Wear'),
    (N'Bobby Bonnet'),
    (N'The Bare Necessities'),
    (N'The Fiery Phoenix'),
    (N'Unforgiven Glory'),
    (N'Texas Toast'),
    (N'The Peacebreaker'),
    (N'Bumble Beenie'),
    (N'Citizen Cane'),
    (N'Gingerbread Mann'),
    (N'Glittering Garland'),
    (N'Pebbles the Penguin'),
    (N'Pocket-Medes'),
    (N'Spiky Viking'),
    (N'The Missing Piece'),
    (N'Yule Hog'),
    (N'Discovision'),
    (N'Globetrotter'),
    (N'Telefragger Toque'),
    (N'The Mislaid Sweater'),
    (N'Winter Wrap Up'),
    (N'Provisions Cap'),
    (N'Public Speaker'),
    (N'Smissmas Saxton'),
    (N'Candy Crown'),
    (N'Antarctic Eyewear'),
    (N'Assassin''s Attire'),
    (N'Sky High Fly Guy'),
    (N'The Head Hedge'),
    (N'The Hot Case'),
    (N'The Tundra Top'),
    (N'Tsar Platinum'),
    (N'Wipe Out Wraps'),
    (N'Aristotle'),
    (N'Blizzard Britches'),
    (N'Punk''s Pomp'),
    (N'Scourge of the Sky'),
    (N'Starboard Crusader'),
    (N'The Burning Question'),
    (N'Veteran''s Attire'),
    (N'Private Maggot Muncher'),
    (N'The Cold Case'),
    (N'The Frag Proof Fragger'),
    (N'Robin Walkers'),
    (N'Bandit''s Boots'),
    (N'Deadbeats'),
    (N'Hephaistos'' Handcraft'),
    (N'Highway Star'),
    (N'Mann-O-War'),
    (N'Mini-Engy'),
    (N'Murderer''s Motif'),
    (N'Olympic Leapers'),
    (N'The Arachno-Arsonist'),
    (N'Vampire Vanquisher'),
    (N'Aim Assistant'),
    (N'Athenian Attire'),
    (N'Dressperado'),
    (N'Gaelic Glutton'),
    (N'Pyro in Chinatown'),
    (N'The Tank Top'),
    (N'Defragmenting Hard Hat 17%'),
    (N'Mr. Quackers'),
    (N'Terror-Antula'),
    (N'Lucky Cat Hat'),
    (N'Climbing Commander'),
    (N'Juvenile''s Jumper'),
    (N'Mighty Mitre'),
    (N'Paka Parka'),
    (N'Pocket Pardner'),
    (N'Snowcapped'),
    (N'The Catcher''s Companion'),
    (N'The Crack Pot'),
    (N'Wise Whiskers'),
    (N'Cool Capuchon'),
    (N'Harry'),
    (N'Miser''s Muttonchops'),
    (N'Pocket Admin'),
    (N'The Puggyback'),
    (N'Millennial Mercenary'),
    (N'The Dumb Bell'),
    (N'The Polar Pal'),
    (N'Bread Heads'),
    (N'Attack Packs'),
    (N'Bait and Bite'),
    (N'Conagher''s Utility Idol'),
    (N'Fireman''s Essentials'),
    (N'Forest Footwear'),
    (N'The Classy Capper'),
    (N'The Most Dangerous Mane'),
    (N'The Nuke'),
    (N'The Pithy Professional'),
    (N'The Shellmet'),
    (N'D-Eye-Monds'),
    (N'Rifleman''s Regalia'),
    (N'The Croaking Hazard'),
    (N'The Hunter in Darkness'),
    (N'Transparent Trousers'),
    (N'Jungle Jersey'),
    (N'The Aztec Aggressor'),
    (N'Tropical Toad'),
    (N'Quizzical Quetzal'),
    (N'The War Eagle'),
    (N'Airborne Attire'),
    (N'Airtight Arsonist'),
    (N'Blast Defense'),
    (N'Field Practice'),
    (N'Flakcatcher'),
    (N'Head Mounted Double Observatory'),
    (N'Speedster''s Spandex'),
    (N'The Upgrade'),
    (N'Warhood'),
    (N'Archer''s Sterling'),
    (N'Down Under Duster'),
    (N'Hawk-Eyed Hunter'),
    (N'Messenger''s Mail Bag'),
    (N'Pocket Pauling'),
    (N'Guilden Guardian'),
    (N'Legendary Lid'),
    (N'Plumber''s Cap'),
    (N'Flash of Inspiration'),
    (N'The Lightning Lid'),
    (N'Aloha Apparel'),
    (N'Battle Boonie'),
    (N'Commando Elite'),
    (N'Deity''s Dress'),
    (N'Fat Man''s Field Cap'),
    (N'Heavy Harness'),
    (N'Sharp Chest Pain'),
    (N'Siberian Tigerstripe'),
    (N'The Cammy Jammies'),
    (N'Vitals Vest'),
    (N'Feathered Fiend'),
    (N'Pocket Saxton'),
    (N'The Conspicuous Camouflage'),
    (N'The Crit Cloak'),
    (N'The Hot Huaraches'),
    (N'Bananades'),
    (N'Jungle Wreath'),
    (N'Sacrificial Stone'),
    (N'The Aztec Warrior'),
    (N'The Slithering Scarf'),
    (N'Blast Blocker'),
    (N'Brass Bucket'),
    (N'Down Tundra Coat'),
    (N'Pocket Santa'),
    (N'Pocket Yeti'),
    (N'Polar Bear'),
    (N'Puffy Polar Cap'),
    (N'The Caribou Companion'),
    (N'The Sinner''s Shade'),
    (N'Trucker''s Topper'),
    (N'Burning Beanie'),
    (N'Coldfront Commander'),
    (N'Melody Of Misery'),
    (N'Sledder''s Sidekick'),
    (N'Wild West Whiskers'),
    (N'Coldfront Carapace'),
    (N'The Cat''s Pajamas'),
    (N'The Handsome Hitman'),
    (N'Balloonihoodie'),
    (N'Hungover Hero'),
    (N'Colossal Cranium'),
    (N'Mad Mask'),
    (N'Nasty Norsemann'),
    (N'Showstopper'),
    (N'Spooktacles'),
    (N'The Cranial Carcharodon'),
    (N'The El Paso Poncho'),
    (N'The Surgeon''s Sidearms'),
    (N'The Wide-Brimmed Bandito'),
    (N'The Wing Mann'),
    (N'Big Topper'),
    (N'Heavy Tourism'),
    (N'Lil'' Bitey'),
    (N'Spirit of the Bombing Past'),
    (N'The Corpus Christi Cranium'),
    (N'The Toadstool Topper'),
    (N'Burly Beast'),
    (N'Mo''Horn'),
    (N'Pestering Jester'),
    (N'Class Crown'),
    (N'Combustible Cutie'),
    (N'Courtly Cuirass'),
    (N'Squire''s Sabatons'),
    (N'The Airdog'),
    (N'The Demo''s Dustcatcher'),
    (N'The Scoped Spartan'),
    (N'The Surgical Survivalist'),
    (N'Herald''s Helm'),
    (N'The Gauzed Gaze'),
    (N'The Lurking Legionnaire'),
    (N'The Patriot''s Pouches'),
    (N'Dad Duds'),
    (N'The Dayjogger'),
    (N'Bedouin Bandana'),
    (N'The Dead Head'),
    (N'Brain-Warming Wear'),
    (N'Elf Esteem'),
    (N'Handy Canes'),
    (N'Packable Provisions'),
    (N'Reader''s Choice'),
    (N'Santarchimedes'),
    (N'Sweet Smissmas Sweater'),
    (N'Bomb Beanie'),
    (N'Flammable Favor'),
    (N'Socked and Loaded'),
    (N'The Electric Twanger'),
    (N'Woolen Warmer'),
    (N'Pyro the Flamedeer'),
    (N'Snowwing'),
    (N'The Head Prize'),
    (N'The Bomber Knight'),
    (N'The Snowmann'),
    (N'A Head Full of Hot Air'),
    (N'Cadet Visor'),
    (N'The Graylien'),
    (N'The Space Diver'),
    (N'Jupiter Jetpack'),
    (N'Phononaut'),
    (N'The C.A.P.P.E.R'),
    (N'Space Hamster Hammy'),
    (N'Taunt: Burstchester'),
    (N'Batsaber'),
    (N'B''aaarrgh-n-Britches'),
    (N'El Patron'),
    (N'Prehistoric Pullover'),
    (N'Roboot'),
    (N'Smokey Sombrero'),
    (N'The Face of Mercy'),
    (N'The Hellmet'),
    (N'Thrilling Tracksuit'),
    (N'B''aaarrgh-n-Bicorne'),
    (N'Death Racer''s Helmet'),
    (N'Duck Billed Hatypus'),
    (N'El Caballero'),
    (N'Iron Lung'),
    (N'Neptune''s Nightmare'),
    (N'Crusader''s Getup'),
    (N'Dead''er Alive'),
    (N'Grim Tweeter'),
    (N'Arthropod''s Aspect'),
    (N'Catastrophic Companions'),
    (N'Commissar''s Coat'),
    (N'Flak Jack'),
    (N'Lurker''s Leathers'),
    (N'Support Spurs'),
    (N'The Rotation Sensation'),
    (N'The Vascular Vestment'),
    (N'Wild West Waistcoat'),
    (N'Fortunate Son'),
    (N'Outta'' Sight'),
    (N'The Physician''s Protector'),
    (N'White Russian'),
    (N'Bruce''s Bonnet'),
    (N'El Duderino'),
    (N'Sheriff''s Stetson'),
    (N'Captain Cardbeard Cutthroat'),
    (N'Potassium Bonnet'),
    (N'Final Frontiersman'),
    (N'Life Support System'),
    (N'Phobos Filter'),
    (N'Universal Translator'),
    (N'Captain Space Mann'),
    (N'Rocket Operator'),
    (N'The Shooting Star'),
    (N'Starduster'),
    (N'The Giger Counter'),
    (N'Corona Australis'),
    (N'Sucker Slug'),
    (N'A Hat to Kill For'),
    (N'Berlin Brain Bowl'),
    (N'Bunnyhopper''s Ballistics Vest'),
    (N'Chicago Overcoat'),
    (N'Hot Heels'),
    (N'Medical Monarch'),
    (N'Shin Shredders'),
    (N'Siberian Sweater'),
    (N'The Diplomat'),
    (N'The Patriot Peak'),
    (N'Bonk Batter''s Backup'),
    (N'The Chill Chullo'),
    (N'The Gift Bringer'),
    (N'Winter Backup'),
    (N'A Well Wrapped Hat');

BEGIN TRY
    BEGIN TRANSACTION;

    INSERT INTO dbo.product
    (
        game_id,
        name,
        rating,
        is_active,
        user_id
    )
    SELECT
        @GameId,
        names.name,
        NULL,
        CAST(1 AS bit),
        @UserId
    FROM @ProductNames AS names
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM dbo.product AS product WITH (UPDLOCK, HOLDLOCK)
        WHERE product.game_id = @GameId
          AND product.user_id = @UserId
          AND product.name = names.name
    );

    SET @InsertedProducts = @@ROWCOUNT;

    INSERT INTO dbo.product_tags
    (
        product_id,
        tag_id
    )
    SELECT
        product.id,
        @TagId
    FROM dbo.product AS product
    INNER JOIN @ProductNames AS names
        ON names.name = product.name
    WHERE product.game_id = @GameId
      AND product.user_id = @UserId
      AND NOT EXISTS
      (
          SELECT 1
          FROM dbo.product_tags AS productTag WITH (UPDLOCK, HOLDLOCK)
          WHERE productTag.product_id = product.id
            AND productTag.tag_id = @TagId
      );

    SET @InsertedProductTags = @@ROWCOUNT;

    COMMIT TRANSACTION;

    SELECT
        @GameId AS game_id,
        @TagId AS tag_id,
        @InsertedProducts AS inserted_products,
        @InsertedProductTags AS inserted_product_tags;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;
