-- Run after add-tf2-hat-products.sql, using the same @UserId.
-- Adds collection-name and plain year tags; preserves Hat and all other tags.
-- Source: tf2_cosmetic_case_collections.xlsx, Cosmetics!A2:D746.
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @UserId nvarchar(450) = N'REPLACE_WITH_USER_ID';
DECLARE @GameId bigint;
DECLARE @InsertedTags int = 0;
DECLARE @InsertedProductTags int = 0;

IF @UserId = N'REPLACE_WITH_USER_ID' OR NULLIF(LTRIM(RTRIM(@UserId)), N'') IS NULL
    THROW 50000, 'Set @UserId before running this script.', 1;

DECLARE @ProductCollections table
(
    product_name nvarchar(255) NOT NULL PRIMARY KEY,
    collection_name nvarchar(255) NOT NULL,
    collection_year int NOT NULL
);

INSERT INTO @ProductCollections (product_name, collection_name, collection_year)
VALUES
    (N'Bald Spotter', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Barbeque Bacon Britches', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Inglorious Patriot', N'Summer 2026 Cosmetics Collection', 2026),
    (N'The Deadliest Match', N'Summer 2026 Cosmetics Collection', 2026),
    (N'The Long Shot', N'Summer 2026 Cosmetics Collection', 2026),
    (N'The Night Riders', N'Summer 2026 Cosmetics Collection', 2026),
    (N'The Unknown Warrior', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Tropical Torcher', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Unruly Ruler', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Vested Investor''s Vest', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Atomic Bomber', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Bomb Blanket', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Delusions of Grandeur', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Lieutenant''s Cut', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Standing Offer', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Surgical Shroud', N'Summer 2026 Cosmetics Collection', 2026),
    (N'The Handsome Ranger', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Tsar Athlete', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Beachcomber''s Brim', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Bonk! Atomic Kicks', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Chief Executor', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Deadwave Communicator', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Hard Hearing', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Pyro''s Overalls', N'Summer 2026 Cosmetics Collection', 2026),
    (N'Air Exchanger', N'Spectral Stash Collection', 2025),
    (N'Feathered Foe', N'Spectral Stash Collection', 2025),
    (N'Poncho del Pesado', N'Spectral Stash Collection', 2025),
    (N'Professor Photon', N'Spectral Stash Collection', 2025),
    (N'Seamann''s Stubble', N'Spectral Stash Collection', 2025),
    (N'Service Satchel', N'Spectral Stash Collection', 2025),
    (N'Technician''s Tunic', N'Spectral Stash Collection', 2025),
    (N'The Misdirector', N'Spectral Stash Collection', 2025),
    (N'Torn Terror', N'Spectral Stash Collection', 2025),
    (N'Viscera Visor', N'Spectral Stash Collection', 2025),
    (N'El Gigante''s Gunbelt', N'Spectral Stash Collection', 2025),
    (N'Heat Shield', N'Spectral Stash Collection', 2025),
    (N'Industrial Insurgent', N'Spectral Stash Collection', 2025),
    (N'Mad Drip', N'Spectral Stash Collection', 2025),
    (N'Pantaloons of Unabashed Villainy', N'Spectral Stash Collection', 2025),
    (N'Ripped Runts', N'Spectral Stash Collection', 2025),
    (N'Sleight of Hand', N'Spectral Stash Collection', 2025),
    (N'Buzz Kill', N'Spectral Stash Collection', 2025),
    (N'Cigarillo Caballero', N'Spectral Stash Collection', 2025),
    (N'Vanishing Act', N'Spectral Stash Collection', 2025),
    (N'Velveteen Villain', N'Spectral Stash Collection', 2025),
    (N'Fused Plates', N'Spectral Stash Collection', 2025),
    (N'Hellscape', N'Spectral Stash Collection', 2025),
    (N'Cattleman''s Kettle', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Clinical Investigator', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Esprit De Corps', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Frogmann''s Fittings', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Hunk Of Monk', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Jarhead', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Le Sapeur', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Mann of the Hour', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Shady Shelby', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Spy Ties', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Blindin'' Bonnett', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Fat Friar', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Hardcore Pantalon', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Le Morne Uniforme', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Oxygen Provider', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Shadow of Doubt', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Sir Buildsalot', N'Summer 2025 Cosmetics Collection', 2025),
    (N'The Headliner', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Case of the Blues', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Mr. Rostov', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Short Fuse', N'Summer 2025 Cosmetics Collection', 2025),
    (N'The Abyss Diver', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Team Cap', N'Summer 2025 Cosmetics Collection', 2025),
    (N'Air Head', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Alpine Apparel', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Black Tie Affair', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Deserter''s Duster', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Epilogue Locks', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Lazer Gazers', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Puncher''s Polar Puffer', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Scrub Stompers', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Snow Merc', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Sydney Shearling', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Alpine Hawk', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Aristocravat', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Chill-Seeker', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Commonwealth Commander', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Festive Fleece', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Flatline Flatcap', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Scrooge McCrocket', N'Winter 2025 Cosmetics Collection', 2025),
    (N'The Sole Providers', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Blizzard Bonnet', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Cardiologist''s Cardigan', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Veteran''s Visor', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Willis'' Warmer', N'Winter 2025 Cosmetics Collection', 2025),
    (N'The Old Days Devotion', N'Winter 2025 Cosmetics Collection', 2025),
    (N'Brute''s Braces', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Commonwealth Commando', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Daring Dell', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Desk Engineer', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Invisible Flame', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Pathfinder', N'Summer 2024 Cosmetics Collection', 2024),
    (N'The Aimframe', N'Summer 2024 Cosmetics Collection', 2024),
    (N'The Brand Loyalist', N'Summer 2024 Cosmetics Collection', 2024),
    (N'The Vaudeville Visor', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Watchmann''s Wetsuit', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Crook''s Cap', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Justice Johns', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Scorched Earth Stompers', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Sneaky Blinder', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Tanker''s Top', N'Summer 2024 Cosmetics Collection', 2024),
    (N'The Big Star', N'Summer 2024 Cosmetics Collection', 2024),
    (N'The Tropical Brim', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Control Patrol', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Fire Marshal', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Free Mann''s Fashion', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Tuxedo Royale', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Botler 2000', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Hazardous Environment Vest', N'Summer 2024 Cosmetics Collection', 2024),
    (N'Defaced Detonator', N'Terrifying Trove Collection', 2024),
    (N'Dusk Duster', N'Terrifying Trove Collection', 2024),
    (N'Fleet Commander', N'Terrifying Trove Collection', 2024),
    (N'Mannhattan Protect', N'Terrifying Trove Collection', 2024),
    (N'Nightfall Veil', N'Terrifying Trove Collection', 2024),
    (N'School Nuisance', N'Terrifying Trove Collection', 2024),
    (N'Spider Sights', N'Terrifying Trove Collection', 2024),
    (N'The Strikeout', N'Terrifying Trove Collection', 2024),
    (N'The Witch Doctor', N'Terrifying Trove Collection', 2024),
    (N'Triboniophorus Gentlemannus', N'Terrifying Trove Collection', 2024),
    (N'Delldozer', N'Terrifying Trove Collection', 2024),
    (N'Hellish Overlord', N'Terrifying Trove Collection', 2024),
    (N'Nuclear Necessity', N'Terrifying Trove Collection', 2024),
    (N'Shadow Shroud', N'Terrifying Trove Collection', 2024),
    (N'Strigoi Stare', N'Terrifying Trove Collection', 2024),
    (N'The Surgeon General', N'Terrifying Trove Collection', 2024),
    (N'Badlands Bandido', N'Terrifying Trove Collection', 2024),
    (N'Chiromancer''s Kit', N'Terrifying Trove Collection', 2024),
    (N'Contaminated Carryall', N'Terrifying Trove Collection', 2024),
    (N'Duality of Mantle', N'Terrifying Trove Collection', 2024),
    (N'Sear Seer', N'Terrifying Trove Collection', 2024),
    (N'Commanding Presence', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Consigliere''s Coverup', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Dapper Noel', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Field Fatigues', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Hot Spaniel', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Poleur Voyeur', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Snug Sharpshooter', N'Winter 2024 Cosmetics Collection', 2024),
    (N'The Battle Music', N'Winter 2024 Cosmetics Collection', 2024),
    (N'The Crimbo Cap', N'Winter 2024 Cosmetics Collection', 2024),
    (N'The Westcoat', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Buck''s Brim', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Cossack Camo', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Frostbite Fit', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Le Frosteaux', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Mine Sweepers', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Polar Charger', N'Winter 2024 Cosmetics Collection', 2024),
    (N'The Checkered Past', N'Winter 2024 Cosmetics Collection', 2024),
    (N'The Triple Jumper', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Battle Balaclava', N'Winter 2024 Cosmetics Collection', 2024),
    (N'L''aire Filteure', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Scrooge McDoc', N'Winter 2024 Cosmetics Collection', 2024),
    (N'The Top Brass', N'Winter 2024 Cosmetics Collection', 2024),
    (N'The Necroprancer', N'Winter 2024 Cosmetics Collection', 2024),
    (N'Concealed Convict', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Constructor''s Cover', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Ludicrously Lunatic Lunon Fedora', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Medical Mummy', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Shortness Of Breath', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Six-Eyed Specs', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Splitting Headache', N'Bone-Chilling Bonanza Collection', 2023),
    (N'The Make Ogre', N'Bone-Chilling Bonanza Collection', 2023),
    (N'The Mean Captain', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Thunder Dome', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Classic Criminal', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Dead Heat', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Dell Dynamic', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Jumping Jester', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Sharpshooter''s Shroud', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Stunt Suit', N'Bone-Chilling Bonanza Collection', 2023),
    (N'The Main Cast', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Warlock''s Warcloak', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Clown''s Cover-Up', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Mad Lad', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Power Spike', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Sightseer', N'Bone-Chilling Bonanza Collection', 2023),
    (N'The Last Laugh', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Bare Bear Bones', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Demonic Dome', N'Bone-Chilling Bonanza Collection', 2023),
    (N'Brimmed Bootlegger', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Brothers in Blues', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Cargo Constructor', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Heavy Metal', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Le Professionnel', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Medical Emergency', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Stealth Bomber', N'Summer 2023 Cosmetics Collection', 2023),
    (N'The Blast Bowl', N'Summer 2023 Cosmetics Collection', 2023),
    (N'The Bushman', N'Summer 2023 Cosmetics Collection', 2023),
    (N'The Firestalker', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Cleaner''s Cap', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Close Quarters Cover', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Hazard Handler', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Hog Heels', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Preventative Measure', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Prohibition Opposition', N'Summer 2023 Cosmetics Collection', 2023),
    (N'The Shrapnel Shell', N'Summer 2023 Cosmetics Collection', 2023),
    (N'The Soho Sleuth', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Brother Mann', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Cranium Cover', N'Summer 2023 Cosmetics Collection', 2023),
    (N'The Flame Warrior', N'Summer 2023 Cosmetics Collection', 2023),
    (N'The Glorious Gambeson', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Über-Wear', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Cranium Cooler', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Full Metal Helmet', N'Summer 2023 Cosmetics Collection', 2023),
    (N'Balkan''s Brute', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Bigger Mann on Campus', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Cozy Cover-Up', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Impact Impaler', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Nightcap', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Rugged Rags', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Sleuth Suit', N'Winter 2023 Cosmetics Collection', 2023),
    (N'The Covert Covers', N'Winter 2023 Cosmetics Collection', 2023),
    (N'The Puffed Practitioner', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Wanderer''s Wool', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Clue Hairdo', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Isotopic Insulator', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Slumber Slacks', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Strasbourg Scholar', N'Winter 2023 Cosmetics Collection', 2023),
    (N'The Frigid Fashion', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Torcher''s Trench Coat', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Trench Warfarer', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Bonk Beanie', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Lazy Lounger', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Masked Loyalty', N'Winter 2023 Cosmetics Collection', 2023),
    (N'The Dapper Dickens', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Boarder''s Beanie', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Scruffed ''n Stitched', N'Winter 2023 Cosmetics Collection', 2023),
    (N'Beaten and Bruised', N'Ghoulish Gains Collection', 2022),
    (N'Bombard Brigadier', N'Ghoulish Gains Collection', 2022),
    (N'Firearm Protector', N'Ghoulish Gains Collection', 2022),
    (N'Horror Shawl', N'Ghoulish Gains Collection', 2022),
    (N'Hunting Cloak', N'Ghoulish Gains Collection', 2022),
    (N'More Gun Marshal', N'Ghoulish Gains Collection', 2022),
    (N'Nightbane Brim', N'Ghoulish Gains Collection', 2022),
    (N'Starlight Sorcerer', N'Ghoulish Gains Collection', 2022),
    (N'The Imp''s Imprint', N'Ghoulish Gains Collection', 2022),
    (N'The Turncoat', N'Ghoulish Gains Collection', 2022),
    (N'Dustbowl Devil', N'Ghoulish Gains Collection', 2022),
    (N'Headhunter''s Brim', N'Ghoulish Gains Collection', 2022),
    (N'Road Block', N'Ghoulish Gains Collection', 2022),
    (N'Safety Stripes', N'Ghoulish Gains Collection', 2022),
    (N'The Lavish Labwear', N'Ghoulish Gains Collection', 2022),
    (N'The Masked Fiend', N'Ghoulish Gains Collection', 2022),
    (N'Alcoholic Automaton', N'Ghoulish Gains Collection', 2022),
    (N'Cranial Cowl', N'Ghoulish Gains Collection', 2022),
    (N'Road Rage', N'Ghoulish Gains Collection', 2022),
    (N'Victorian Villainy', N'Ghoulish Gains Collection', 2022),
    (N'Propaniac', N'Ghoulish Gains Collection', 2022),
    (N'The Onimann', N'Ghoulish Gains Collection', 2022),
    (N'Barefoot Brawler', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Combat Casual', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Hawaiian Hunter', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Pest''s Pads', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Tactical Turtleneck', N'Summer 2022 Cosmetics Collection', 2022),
    (N'The Chaser', N'Summer 2022 Cosmetics Collection', 2022),
    (N'The Team Player', N'Summer 2022 Cosmetics Collection', 2022),
    (N'The Throttlehead', N'Summer 2022 Cosmetics Collection', 2022),
    (N'The Western Wraps', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Undercover Brolly', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Boston Brain Bucket', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Fizzy Pharmacist', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Squatter''s Right', N'Summer 2022 Cosmetics Collection', 2022),
    (N'The Detective', N'Summer 2022 Cosmetics Collection', 2022),
    (N'The Hawaiian Hangover', N'Summer 2022 Cosmetics Collection', 2022),
    (N'The Lawnmaker', N'Summer 2022 Cosmetics Collection', 2022),
    (N'The Ripped Rider', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Tropical Camo', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Head Banger', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Kazan Karategi', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Monsieur Grenouille', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Night Vision Gawkers', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Soda Cap', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Rocko', N'Summer 2022 Cosmetics Collection', 2022),
    (N'The Decorated Veteran', N'Summer 2022 Cosmetics Collection', 2022),
    (N'Arctic Mole', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Bulb Bonnet', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Cold Blooded Coat', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Crosshair Cardigan', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Glasgow Bankroll', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Heavy Heating', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Lumbercap', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Oktoberfester', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Partizan', N'Winter 2022 Cosmetics Collection', 2022),
    (N'The Soft Hard Hat', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Firebrand', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Frostbite Bonnet', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Infiltrator''s Insulation', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Ol'' Reliable', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Plaid Lad', N'Winter 2022 Cosmetics Collection', 2022),
    (N'The Cool Warm Sweater', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Underminer''s Overcoat', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Battle Bear', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Colonel Kringle', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Motley Sleeves', N'Winter 2022 Cosmetics Collection', 2022),
    (N'The Wooly Pulli', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Festive Rack', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Trapper''s Flap', N'Winter 2022 Cosmetics Collection', 2022),
    (N'Beanie The All-Gnawing', N'Crimson Cache Collection', 2021),
    (N'Creepy Crawlers', N'Crimson Cache Collection', 2021),
    (N'Death Stare', N'Crimson Cache Collection', 2021),
    (N'Hat Outta Hell', N'Crimson Cache Collection', 2021),
    (N'Smiling Somen', N'Crimson Cache Collection', 2021),
    (N'Spooky Head-Bouncers', N'Crimson Cache Collection', 2021),
    (N'The Scariest Mask EVER', N'Crimson Cache Collection', 2021),
    (N'Trickster''s Treats', N'Crimson Cache Collection', 2021),
    (N'Twisted Topper', N'Crimson Cache Collection', 2021),
    (N'Alakablamicon', N'Crimson Cache Collection', 2021),
    (N'Eyequarium', N'Crimson Cache Collection', 2021),
    (N'Goalkeeper', N'Crimson Cache Collection', 2021),
    (N'Optic Nerve', N'Crimson Cache Collection', 2021),
    (N'Second-Head Headwear', N'Crimson Cache Collection', 2021),
    (N'The Hook, Line, and Thinker', N'Crimson Cache Collection', 2021),
    (N'Gruesome Gourd', N'Crimson Cache Collection', 2021),
    (N'The Bone Cone', N'Crimson Cache Collection', 2021),
    (N'Wandering Wraith', N'Crimson Cache Collection', 2021),
    (N'Towering Patch of Pumpkins', N'Crimson Cache Collection', 2021),
    (N'Brim of Fire', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Fried Batter', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Hook, Line, and Cinder', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Manndatory Attire', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Reel Fly Hat', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Roaming Roman', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Thousand-Yard Stare', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Two Punch Mann', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Wild Brim Slouch', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Crocodile Dandy', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Meal Dealer', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Snack Stack', N'Summer 2021 Cosmetics Collection', 2021),
    (N'The Sightliner', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Water Waders', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Crustaceous Cowl', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Fast Food', N'Summer 2021 Cosmetics Collection', 2021),
    (N'The Panisher', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Ballooniphones', N'Summer 2021 Cosmetics Collection', 2021),
    (N'Brain Cane', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Cozy Catchers', N'Winter 2021 Cosmetics Collection', 2021),
    (N'El Fiestibrero', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Elf Defense', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Festive Cover-Up', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Festive Frames', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Gnome Dome', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Mooshanka', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Ominous Offering', N'Winter 2021 Cosmetics Collection', 2021),
    (N'The Giftcrafter', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Elf Ignition', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Elf-Made Bandanna', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Reindoonihorns', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Seasonal Employee', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Seasonal Spring', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Train Of Thought', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Hat Chocolate', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Jolly Jester', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Merry Cone', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Oh Deer!', N'Winter 2021 Cosmetics Collection', 2021),
    (N'Bazaar Bauble', N'Summer 2020 Cosmetics Collection', 2020),
    (N'California Cap', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Crabe de Chapeau', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Fire Fighter', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Head Of Defense', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Poolside Polo', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Self-Care', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Soda Specs', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Sophisticated Smoker', N'Summer 2020 Cosmetics Collection', 2020),
    (N'The Jarmaments', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Bird''s Eye Viewer', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Breach and Bomb', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Flatliner', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Hazard Headgear', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Momma Kiev', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Tools of the Tourist', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Flamehawk', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Hawk Warrior', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Loaf Loafers', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Smoking Jacket', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Breadcrab', N'Summer 2020 Cosmetics Collection', 2020),
    (N'Hypno-Eyes', N'Summer 2020 Cosmetics Collection', 2020),
    (N'A Handsome Handy Thing', N'Wicked Windfall Collection', 2020),
    (N'Calamitous Cauldron', N'Wicked Windfall Collection', 2020),
    (N'Flavorful Baggies', N'Wicked Windfall Collection', 2020),
    (N'Goblineer', N'Wicked Windfall Collection', 2020),
    (N'Handsome Devil', N'Wicked Windfall Collection', 2020),
    (N'Hollowed Helm', N'Wicked Windfall Collection', 2020),
    (N'King Cardbeard', N'Wicked Windfall Collection', 2020),
    (N'The Boom Boxers', N'Wicked Windfall Collection', 2020),
    (N'The Ghoul Box', N'Wicked Windfall Collection', 2020),
    (N'The Seared Sorcerer', N'Wicked Windfall Collection', 2020),
    (N'Eye-See-You', N'Wicked Windfall Collection', 2020),
    (N'Glow from Below', N'Wicked Windfall Collection', 2020),
    (N'Gourd Grin', N'Wicked Windfall Collection', 2020),
    (N'Impish Ears', N'Wicked Windfall Collection', 2020),
    (N'Semi-Tame Trapper''s Hat', N'Wicked Windfall Collection', 2020),
    (N'Sir Pumpkinton', N'Wicked Windfall Collection', 2020),
    (N'Misfortune Fedora', N'Wicked Windfall Collection', 2020),
    (N'The Fire Tooth', N'Wicked Windfall Collection', 2020),
    (N'Wavefinder', N'Wicked Windfall Collection', 2020),
    (N'Wrap-A-Khamon', N'Wicked Windfall Collection', 2020),
    (N'All Hallows'' Hatte', N'Wicked Windfall Collection', 2020),
    (N'Balloonicorpse', N'Wicked Windfall Collection', 2020),
    (N'Bear Walker', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Candy Cantlers', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Elf Care Provider', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Festive Fascinator', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Festive Flip-thwomps', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Jolly Jingler', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Particulate Protector', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Reindoonibeanie', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Shoestring Santa', N'Winter 2020 Cosmetics Collection', 2020),
    (N'The Killing Tree', N'Winter 2020 Cosmetics Collection', 2020),
    (N'BedBug Protection', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Blitzen Bowl', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Night Ward', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Professional''s Pom-Pom', N'Winter 2020 Cosmetics Collection', 2020),
    (N'SandMann''s Brush', N'Winter 2020 Cosmetics Collection', 2020),
    (N'The Smissmas Sorcerer', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Helm Helm', N'Winter 2020 Cosmetics Collection', 2020),
    (N'The Round-A-Bout', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Towering Pillar of Beanies', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Towering Pile Of Presents', N'Winter 2020 Cosmetics Collection', 2020),
    (N'Bat Hat', N'Spooky Spoils Collection', 2019),
    (N'BINOCULUS!', N'Spooky Spoils Collection', 2019),
    (N'Bread Biter', N'Spooky Spoils Collection', 2019),
    (N'Candy Cranium', N'Spooky Spoils Collection', 2019),
    (N'Convict Cap', N'Spooky Spoils Collection', 2019),
    (N'Derangement Garment', N'Spooky Spoils Collection', 2019),
    (N'El Mostacho', N'Spooky Spoils Collection', 2019),
    (N'Fuel Injector', N'Spooky Spoils Collection', 2019),
    (N'Party Poncho', N'Spooky Spoils Collection', 2019),
    (N'Pocket Halloween Boss', N'Spooky Spoils Collection', 2019),
    (N'El Zapateador', N'Spooky Spoils Collection', 2019),
    (N'Madmann''s Muzzle', N'Spooky Spoils Collection', 2019),
    (N'Skullbrero', N'Spooky Spoils Collection', 2019),
    (N'Soviet Strongmann', N'Spooky Spoils Collection', 2019),
    (N'The Horrible Horns', N'Spooky Spoils Collection', 2019),
    (N'Voodoo Vizier', N'Spooky Spoils Collection', 2019),
    (N'Elizabeth the Third', N'Spooky Spoils Collection', 2019),
    (N'Head of the Dead', N'Spooky Spoils Collection', 2019),
    (N'Racc Mann', N'Spooky Spoils Collection', 2019),
    (N'The Trick Stabber', N'Spooky Spoils Collection', 2019),
    (N'Mister Bones', N'Spooky Spoils Collection', 2019),
    (N'Pyr''o Lantern', N'Spooky Spoils Collection', 2019),
    (N'Backbreaker''s Guards', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Brain Interface', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Dancing Doe', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Mediterranean Mercenary', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Melted Mop', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Shutterbug', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Stapler''s Specs', N'Summer 2019 Cosmetics Collection', 2019),
    (N'The Bottle Cap', N'Summer 2019 Cosmetics Collection', 2019),
    (N'The Pompous Privateer', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Wanderer''s Wear', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Backbreaker''s Skullcracker', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Dynamite Abs', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Kapitan''s Kaftan', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Spawn Camper', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Speedy Scoundrel', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Wagga Wagga Wear', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Bobby Bonnet', N'Summer 2019 Cosmetics Collection', 2019),
    (N'The Bare Necessities', N'Summer 2019 Cosmetics Collection', 2019),
    (N'The Fiery Phoenix', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Unforgiven Glory', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Texas Toast', N'Summer 2019 Cosmetics Collection', 2019),
    (N'The Peacebreaker', N'Summer 2019 Cosmetics Collection', 2019),
    (N'Bumble Beenie', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Citizen Cane', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Gingerbread Mann', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Glittering Garland', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Pebbles the Penguin', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Pocket-Medes', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Spiky Viking', N'Winter 2019 Cosmetics Collection', 2019),
    (N'The Missing Piece', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Yule Hog', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Discovision', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Globetrotter', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Telefragger Toque', N'Winter 2019 Cosmetics Collection', 2019),
    (N'The Mislaid Sweater', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Winter Wrap Up', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Provisions Cap', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Public Speaker', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Smissmas Saxton', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Candy Crown', N'Winter 2019 Cosmetics Collection', 2019),
    (N'Antarctic Eyewear', N'Blue Moon Cosmetics Collection', 2018),
    (N'Assassin''s Attire', N'Blue Moon Cosmetics Collection', 2018),
    (N'Sky High Fly Guy', N'Blue Moon Cosmetics Collection', 2018),
    (N'The Head Hedge', N'Blue Moon Cosmetics Collection', 2018),
    (N'The Hot Case', N'Blue Moon Cosmetics Collection', 2018),
    (N'The Tundra Top', N'Blue Moon Cosmetics Collection', 2018),
    (N'Tsar Platinum', N'Blue Moon Cosmetics Collection', 2018),
    (N'Wipe Out Wraps', N'Blue Moon Cosmetics Collection', 2018),
    (N'Aristotle', N'Blue Moon Cosmetics Collection', 2018),
    (N'Blizzard Britches', N'Blue Moon Cosmetics Collection', 2018),
    (N'Punk''s Pomp', N'Blue Moon Cosmetics Collection', 2018),
    (N'Scourge of the Sky', N'Blue Moon Cosmetics Collection', 2018),
    (N'Starboard Crusader', N'Blue Moon Cosmetics Collection', 2018),
    (N'The Burning Question', N'Blue Moon Cosmetics Collection', 2018),
    (N'Veteran''s Attire', N'Blue Moon Cosmetics Collection', 2018),
    (N'Private Maggot Muncher', N'Blue Moon Cosmetics Collection', 2018),
    (N'The Cold Case', N'Blue Moon Cosmetics Collection', 2018),
    (N'The Frag Proof Fragger', N'Blue Moon Cosmetics Collection', 2018),
    (N'Robin Walkers', N'Blue Moon Cosmetics Collection', 2018),
    (N'Bandit''s Boots', N'Violet Vermin Collection', 2018),
    (N'Deadbeats', N'Violet Vermin Collection', 2018),
    (N'Hephaistos'' Handcraft', N'Violet Vermin Collection', 2018),
    (N'Highway Star', N'Violet Vermin Collection', 2018),
    (N'Mann-O-War', N'Violet Vermin Collection', 2018),
    (N'Mini-Engy', N'Violet Vermin Collection', 2018),
    (N'Murderer''s Motif', N'Violet Vermin Collection', 2018),
    (N'Olympic Leapers', N'Violet Vermin Collection', 2018),
    (N'The Arachno-Arsonist', N'Violet Vermin Collection', 2018),
    (N'Vampire Vanquisher', N'Violet Vermin Collection', 2018),
    (N'Aim Assistant', N'Violet Vermin Collection', 2018),
    (N'Athenian Attire', N'Violet Vermin Collection', 2018),
    (N'Dressperado', N'Violet Vermin Collection', 2018),
    (N'Gaelic Glutton', N'Violet Vermin Collection', 2018),
    (N'Pyro in Chinatown', N'Violet Vermin Collection', 2018),
    (N'The Tank Top', N'Violet Vermin Collection', 2018),
    (N'Defragmenting Hard Hat 17%', N'Violet Vermin Collection', 2018),
    (N'Mr. Quackers', N'Violet Vermin Collection', 2018),
    (N'Terror-Antula', N'Violet Vermin Collection', 2018),
    (N'Lucky Cat Hat', N'Violet Vermin Collection', 2018),
    (N'Climbing Commander', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Juvenile''s Jumper', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Mighty Mitre', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Paka Parka', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Pocket Pardner', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Snowcapped', N'Winter 2018 Cosmetics Collection', 2018),
    (N'The Catcher''s Companion', N'Winter 2018 Cosmetics Collection', 2018),
    (N'The Crack Pot', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Wise Whiskers', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Cool Capuchon', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Harry', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Miser''s Muttonchops', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Pocket Admin', N'Winter 2018 Cosmetics Collection', 2018),
    (N'The Puggyback', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Millennial Mercenary', N'Winter 2018 Cosmetics Collection', 2018),
    (N'The Dumb Bell', N'Winter 2018 Cosmetics Collection', 2018),
    (N'The Polar Pal', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Bread Heads', N'Winter 2018 Cosmetics Collection', 2018),
    (N'Attack Packs', N'Abominable Cosmetic Collection', 2017),
    (N'Bait and Bite', N'Abominable Cosmetic Collection', 2017),
    (N'Conagher''s Utility Idol', N'Abominable Cosmetic Collection', 2017),
    (N'Fireman''s Essentials', N'Abominable Cosmetic Collection', 2017),
    (N'Forest Footwear', N'Abominable Cosmetic Collection', 2017),
    (N'The Classy Capper', N'Abominable Cosmetic Collection', 2017),
    (N'The Most Dangerous Mane', N'Abominable Cosmetic Collection', 2017),
    (N'The Nuke', N'Abominable Cosmetic Collection', 2017),
    (N'The Pithy Professional', N'Abominable Cosmetic Collection', 2017),
    (N'The Shellmet', N'Abominable Cosmetic Collection', 2017),
    (N'D-Eye-Monds', N'Abominable Cosmetic Collection', 2017),
    (N'Rifleman''s Regalia', N'Abominable Cosmetic Collection', 2017),
    (N'The Croaking Hazard', N'Abominable Cosmetic Collection', 2017),
    (N'The Hunter in Darkness', N'Abominable Cosmetic Collection', 2017),
    (N'Transparent Trousers', N'Abominable Cosmetic Collection', 2017),
    (N'Jungle Jersey', N'Abominable Cosmetic Collection', 2017),
    (N'The Aztec Aggressor', N'Abominable Cosmetic Collection', 2017),
    (N'Tropical Toad', N'Abominable Cosmetic Collection', 2017),
    (N'Quizzical Quetzal', N'Abominable Cosmetic Collection', 2017),
    (N'The War Eagle', N'Abominable Cosmetic Collection', 2017),
    (N'Airborne Attire', N'Rainy Day Cosmetics Collection', 2017),
    (N'Airtight Arsonist', N'Rainy Day Cosmetics Collection', 2017),
    (N'Blast Defense', N'Rainy Day Cosmetics Collection', 2017),
    (N'Field Practice', N'Rainy Day Cosmetics Collection', 2017),
    (N'Flakcatcher', N'Rainy Day Cosmetics Collection', 2017),
    (N'Head Mounted Double Observatory', N'Rainy Day Cosmetics Collection', 2017),
    (N'Speedster''s Spandex', N'Rainy Day Cosmetics Collection', 2017),
    (N'The Upgrade', N'Rainy Day Cosmetics Collection', 2017),
    (N'Warhood', N'Rainy Day Cosmetics Collection', 2017),
    (N'Archer''s Sterling', N'Rainy Day Cosmetics Collection', 2017),
    (N'Down Under Duster', N'Rainy Day Cosmetics Collection', 2017),
    (N'Hawk-Eyed Hunter', N'Rainy Day Cosmetics Collection', 2017),
    (N'Messenger''s Mail Bag', N'Rainy Day Cosmetics Collection', 2017),
    (N'Pocket Pauling', N'Rainy Day Cosmetics Collection', 2017),
    (N'Guilden Guardian', N'Rainy Day Cosmetics Collection', 2017),
    (N'Legendary Lid', N'Rainy Day Cosmetics Collection', 2017),
    (N'Plumber''s Cap', N'Rainy Day Cosmetics Collection', 2017),
    (N'Flash of Inspiration', N'Rainy Day Cosmetics Collection', 2017),
    (N'The Lightning Lid', N'Rainy Day Cosmetics Collection', 2017),
    (N'Aloha Apparel', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Battle Boonie', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Commando Elite', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Deity''s Dress', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Fat Man''s Field Cap', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Heavy Harness', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Sharp Chest Pain', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Siberian Tigerstripe', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'The Cammy Jammies', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Vitals Vest', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Feathered Fiend', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Pocket Saxton', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'The Conspicuous Camouflage', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'The Crit Cloak', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'The Hot Huaraches', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Bananades', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Jungle Wreath', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Sacrificial Stone', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'The Aztec Warrior', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'The Slithering Scarf', N'Unleash the Beast Cosmetic Collection', 2017),
    (N'Blast Blocker', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Brass Bucket', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Down Tundra Coat', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Pocket Santa', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Pocket Yeti', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Polar Bear', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Puffy Polar Cap', N'Winter 2017 Cosmetics Collection', 2017),
    (N'The Caribou Companion', N'Winter 2017 Cosmetics Collection', 2017),
    (N'The Sinner''s Shade', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Trucker''s Topper', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Burning Beanie', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Coldfront Commander', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Melody Of Misery', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Sledder''s Sidekick', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Wild West Whiskers', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Coldfront Carapace', N'Winter 2017 Cosmetics Collection', 2017),
    (N'The Cat''s Pajamas', N'Winter 2017 Cosmetics Collection', 2017),
    (N'The Handsome Hitman', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Balloonihoodie', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Hungover Hero', N'Winter 2017 Cosmetics Collection', 2017),
    (N'Colossal Cranium', N'Creepy Crawly Collection', 2016),
    (N'Mad Mask', N'Creepy Crawly Collection', 2016),
    (N'Nasty Norsemann', N'Creepy Crawly Collection', 2016),
    (N'Showstopper', N'Creepy Crawly Collection', 2016),
    (N'Spooktacles', N'Creepy Crawly Collection', 2016),
    (N'The Cranial Carcharodon', N'Creepy Crawly Collection', 2016),
    (N'The El Paso Poncho', N'Creepy Crawly Collection', 2016),
    (N'The Surgeon''s Sidearms', N'Creepy Crawly Collection', 2016),
    (N'The Wide-Brimmed Bandito', N'Creepy Crawly Collection', 2016),
    (N'The Wing Mann', N'Creepy Crawly Collection', 2016),
    (N'Big Topper', N'Creepy Crawly Collection', 2016),
    (N'Heavy Tourism', N'Creepy Crawly Collection', 2016),
    (N'Lil'' Bitey', N'Creepy Crawly Collection', 2016),
    (N'Spirit of the Bombing Past', N'Creepy Crawly Collection', 2016),
    (N'The Corpus Christi Cranium', N'Creepy Crawly Collection', 2016),
    (N'The Toadstool Topper', N'Creepy Crawly Collection', 2016),
    (N'Burly Beast', N'Creepy Crawly Collection', 2016),
    (N'Mo''Horn', N'Creepy Crawly Collection', 2016),
    (N'Pestering Jester', N'Creepy Crawly Collection', 2016),
    (N'Class Crown', N'Creepy Crawly Collection', 2016),
    (N'Combustible Cutie', N'Creepy Crawly Collection', 2016),
    (N'Courtly Cuirass', N'Mayflower Cosmetics Collection', 2016),
    (N'Squire''s Sabatons', N'Mayflower Cosmetics Collection', 2016),
    (N'The Airdog', N'Mayflower Cosmetics Collection', 2016),
    (N'The Demo''s Dustcatcher', N'Mayflower Cosmetics Collection', 2016),
    (N'The Scoped Spartan', N'Mayflower Cosmetics Collection', 2016),
    (N'The Surgical Survivalist', N'Mayflower Cosmetics Collection', 2016),
    (N'Herald''s Helm', N'Mayflower Cosmetics Collection', 2016),
    (N'The Gauzed Gaze', N'Mayflower Cosmetics Collection', 2016),
    (N'The Lurking Legionnaire', N'Mayflower Cosmetics Collection', 2016),
    (N'The Patriot''s Pouches', N'Mayflower Cosmetics Collection', 2016),
    (N'Dad Duds', N'Mayflower Cosmetics Collection', 2016),
    (N'The Dayjogger', N'Mayflower Cosmetics Collection', 2016),
    (N'Bedouin Bandana', N'Mayflower Cosmetics Collection', 2016),
    (N'The Dead Head', N'Mayflower Cosmetics Collection', 2016),
    (N'Brain-Warming Wear', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Elf Esteem', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Handy Canes', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Packable Provisions', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Reader''s Choice', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Santarchimedes', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Sweet Smissmas Sweater', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Bomb Beanie', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Flammable Favor', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Socked and Loaded', N'Winter 2016 Cosmetics Collection', 2016),
    (N'The Electric Twanger', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Woolen Warmer', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Pyro the Flamedeer', N'Winter 2016 Cosmetics Collection', 2016),
    (N'Snowwing', N'Winter 2016 Cosmetics Collection', 2016),
    (N'The Head Prize', N'Winter 2016 Cosmetics Collection', 2016),
    (N'The Bomber Knight', N'Winter 2016 Cosmetics Collection', 2016),
    (N'The Snowmann', N'Winter 2016 Cosmetics Collection', 2016),
    (N'A Head Full of Hot Air', N'Confidential Collection', 2015),
    (N'Cadet Visor', N'Confidential Collection', 2015),
    (N'The Graylien', N'Confidential Collection', 2015),
    (N'The Space Diver', N'Confidential Collection', 2015),
    (N'Jupiter Jetpack', N'Confidential Collection', 2015),
    (N'Phononaut', N'Confidential Collection', 2015),
    (N'The C.A.P.P.E.R', N'Confidential Collection', 2015),
    (N'Space Hamster Hammy', N'Confidential Collection', 2015),
    (N'Taunt: Burstchester', N'Confidential Collection', 2015),
    (N'Batsaber', N'Confidential Collection', 2015),
    (N'B''aaarrgh-n-Britches', N'Gargoyle Collection', 2015),
    (N'El Patron', N'Gargoyle Collection', 2015),
    (N'Prehistoric Pullover', N'Gargoyle Collection', 2015),
    (N'Roboot', N'Gargoyle Collection', 2015),
    (N'Smokey Sombrero', N'Gargoyle Collection', 2015),
    (N'The Face of Mercy', N'Gargoyle Collection', 2015),
    (N'The Hellmet', N'Gargoyle Collection', 2015),
    (N'Thrilling Tracksuit', N'Gargoyle Collection', 2015),
    (N'B''aaarrgh-n-Bicorne', N'Gargoyle Collection', 2015),
    (N'Death Racer''s Helmet', N'Gargoyle Collection', 2015),
    (N'Duck Billed Hatypus', N'Gargoyle Collection', 2015),
    (N'El Caballero', N'Gargoyle Collection', 2015),
    (N'Iron Lung', N'Gargoyle Collection', 2015),
    (N'Neptune''s Nightmare', N'Gargoyle Collection', 2015),
    (N'Crusader''s Getup', N'Gargoyle Collection', 2015),
    (N'Dead''er Alive', N'Gargoyle Collection', 2015),
    (N'Grim Tweeter', N'Gargoyle Collection', 2015),
    (N'Arthropod''s Aspect', N'Gargoyle Collection', 2015),
    (N'Catastrophic Companions', N'Gargoyle Collection', 2015),
    (N'Commissar''s Coat', N'Gun Mettle Cosmetics Collection', 2015),
    (N'Flak Jack', N'Gun Mettle Cosmetics Collection', 2015),
    (N'Lurker''s Leathers', N'Gun Mettle Cosmetics Collection', 2015),
    (N'Support Spurs', N'Gun Mettle Cosmetics Collection', 2015),
    (N'The Rotation Sensation', N'Gun Mettle Cosmetics Collection', 2015),
    (N'The Vascular Vestment', N'Gun Mettle Cosmetics Collection', 2015),
    (N'Wild West Waistcoat', N'Gun Mettle Cosmetics Collection', 2015),
    (N'Fortunate Son', N'Gun Mettle Cosmetics Collection', 2015),
    (N'Outta'' Sight', N'Gun Mettle Cosmetics Collection', 2015),
    (N'The Physician''s Protector', N'Gun Mettle Cosmetics Collection', 2015),
    (N'White Russian', N'Gun Mettle Cosmetics Collection', 2015),
    (N'Bruce''s Bonnet', N'Gun Mettle Cosmetics Collection', 2015),
    (N'El Duderino', N'Gun Mettle Cosmetics Collection', 2015),
    (N'Sheriff''s Stetson', N'Gun Mettle Cosmetics Collection', 2015),
    (N'Captain Cardbeard Cutthroat', N'Gun Mettle Cosmetics Collection', 2015),
    (N'Potassium Bonnet', N'Gun Mettle Cosmetics Collection', 2015),
    (N'Final Frontiersman', N'Quarantined Collection', 2015),
    (N'Life Support System', N'Quarantined Collection', 2015),
    (N'Phobos Filter', N'Quarantined Collection', 2015),
    (N'Universal Translator', N'Quarantined Collection', 2015),
    (N'Captain Space Mann', N'Quarantined Collection', 2015),
    (N'Rocket Operator', N'Quarantined Collection', 2015),
    (N'The Shooting Star', N'Quarantined Collection', 2015),
    (N'Starduster', N'Quarantined Collection', 2015),
    (N'The Giger Counter', N'Quarantined Collection', 2015),
    (N'Corona Australis', N'Quarantined Collection', 2015),
    (N'Sucker Slug', N'Quarantined Collection', 2015),
    (N'A Hat to Kill For', N'Tough Break Cosmetics Collection', 2015),
    (N'Berlin Brain Bowl', N'Tough Break Cosmetics Collection', 2015),
    (N'Bunnyhopper''s Ballistics Vest', N'Tough Break Cosmetics Collection', 2015),
    (N'Chicago Overcoat', N'Tough Break Cosmetics Collection', 2015),
    (N'Hot Heels', N'Tough Break Cosmetics Collection', 2015),
    (N'Medical Monarch', N'Tough Break Cosmetics Collection', 2015),
    (N'Shin Shredders', N'Tough Break Cosmetics Collection', 2015),
    (N'Siberian Sweater', N'Tough Break Cosmetics Collection', 2015),
    (N'The Diplomat', N'Tough Break Cosmetics Collection', 2015),
    (N'The Patriot Peak', N'Tough Break Cosmetics Collection', 2015),
    (N'Bonk Batter''s Backup', N'Tough Break Cosmetics Collection', 2015),
    (N'The Chill Chullo', N'Tough Break Cosmetics Collection', 2015),
    (N'The Gift Bringer', N'Tough Break Cosmetics Collection', 2015),
    (N'Winter Backup', N'Tough Break Cosmetics Collection', 2015),
    (N'A Well Wrapped Hat', N'Tough Break Cosmetics Collection', 2015)
;

DECLARE @RequiredTags table (name nvarchar(255) NOT NULL PRIMARY KEY);

INSERT INTO @RequiredTags (name)
SELECT collection_name FROM @ProductCollections
UNION
SELECT CONVERT(nvarchar(255), collection_year) FROM @ProductCollections;

BEGIN TRY
    BEGIN TRANSACTION;

    IF (SELECT COUNT(*) FROM dbo.game WITH (UPDLOCK, HOLDLOCK)
        WHERE name = N'Team Fortress 2' AND user_id = @UserId) <> 1
        THROW 50001, 'Expected exactly one Team Fortress 2 game for @UserId.', 1;

    SELECT @GameId = id
    FROM dbo.game
    WHERE name = N'Team Fortress 2' AND user_id = @UserId;

    -- Fail before writing if any cosmetic is missing or matches multiple products.
    IF EXISTS
    (
        SELECT mapping.product_name
        FROM @ProductCollections AS mapping
        LEFT JOIN dbo.product AS product WITH (UPDLOCK, HOLDLOCK)
            ON product.name = mapping.product_name
           AND product.game_id = @GameId
           AND product.user_id = @UserId
        GROUP BY mapping.product_name
        HAVING COUNT(product.id) <> 1
    )
        THROW 50002, 'A cosmetic is missing or duplicated. Run the Hat insert first and resolve duplicate product names.', 1;

    IF EXISTS
    (
        SELECT required.name
        FROM @RequiredTags AS required
        INNER JOIN dbo.tag AS tag WITH (UPDLOCK, HOLDLOCK)
            ON tag.name = required.name
           AND tag.game_id = @GameId
           AND tag.user_id = @UserId
        GROUP BY required.name
        HAVING COUNT(tag.id) > 1
    )
        THROW 50003, 'A required tag name matches multiple tags for this game and owner.', 1;

    INSERT INTO dbo.tag (game_id, name, is_active, user_id, item_group_id)
    SELECT @GameId, required.name, CAST(1 AS bit), @UserId, NULL
    FROM @RequiredTags AS required
    WHERE NOT EXISTS
    (
        SELECT 1 FROM dbo.tag AS tag WITH (UPDLOCK, HOLDLOCK)
        WHERE tag.game_id = @GameId
          AND tag.user_id = @UserId
          AND tag.name = required.name
    );

    SET @InsertedTags = @@ROWCOUNT;

    INSERT INTO dbo.product_tags (product_id, tag_id)
    SELECT DISTINCT product.id, tag.id
    FROM @ProductCollections AS mapping
    INNER JOIN dbo.product AS product
        ON product.name = mapping.product_name
       AND product.game_id = @GameId
       AND product.user_id = @UserId
    CROSS APPLY
    (
        VALUES (mapping.collection_name),
               (CONVERT(nvarchar(255), mapping.collection_year))
    ) AS required(name)
    INNER JOIN dbo.tag AS tag
        ON tag.name = required.name
       AND tag.game_id = @GameId
       AND tag.user_id = @UserId
    WHERE NOT EXISTS
    (
        SELECT 1 FROM dbo.product_tags AS productTag WITH (UPDLOCK, HOLDLOCK)
        WHERE productTag.product_id = product.id
          AND productTag.tag_id = tag.id
    );

    SET @InsertedProductTags = @@ROWCOUNT;

    COMMIT TRANSACTION;

    SELECT @GameId AS game_id,
           (SELECT COUNT(*) FROM @ProductCollections) AS mapped_products,
           (SELECT COUNT(*) FROM @RequiredTags) AS required_tags,
           @InsertedTags AS inserted_tags,
           @InsertedProductTags AS inserted_product_tags;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;
